    //Options
    global.resolution=2;
    global.bgm=1;
    global.fullscreen=1;
    global.vsync=1;
    global.scanlines=0;
    //Scores
    global.highscore0=0
    global.highscore1=0
    global.highscore2=0
    global.highscore3=0
    global.highscore4=0
    global.extra_stage=0
    //Key Binds
    global.Up=vk_up;
    global.Down=vk_down;
    global.Left=vk_left;
    global.Right=vk_right;
    global.Focus=vk_shift;
    global.Shoot=(ord('Z'));
    global.Bomb=(ord('X'));
scr_save();